//
//  SearchControllerRouter.swift
//  GithubSearch
//
//  Created George Kyrylenko on 30.08.2020.
//  Copyright © 2020 TestApp. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SearchControllerRouter: SearchControllerWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = SearchControllerViewController(nibName: nil, bundle: nil)
        let interactor = SearchControllerInteractor()
        let router = SearchControllerRouter()
        let presenter = SearchControllerPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
